name: vesto
root: ~/capsule/vesto/
attach: true
windows:
  - SERVERS:
      layout: even-horizontal
      panes:
        - DJANGO:
          - make up
        - WEBPACK:
          - cd vesto/frontend
          - npm run dev
  - CODE: nvim
  - LAZYGIT: lazygit
