format = """${custom.jj_change} ${custom.jj_description}\
️$directory\
${custom.jj_git_not_insync}\
$git_status$character"""

[git_commit]
only_detached = false

[custom.jj_change]
when = "jj workspace root --ignore-working-copy >/dev/null 2>&1"
style = "none" # keep jj’s own ANSI colors
format = "$output" # don’t wrap in extra brackets/colors
command = "jj-change"

[custom.jj_description]
when = "jj workspace root --ignore-working-copy >/dev/null 2>&1"
style = "none" # keep jj’s own ANSI colors
format = "$output" # don’t wrap in extra brackets/colors
command = "jj-description"

[custom.jj_git_notinsync]
when = '[ -n "${jj_git_head:=$(jj log -T commit_id --no-graph --ignore-working-copy -r HEAD@git)}" ] && [ -n "${git_head:=$(git rev-parse HEAD)}" ] && [ "$git_head" != "$jj_git_head" ]'
command = 'jj log -T "commit_id.short()" --no-graph --ignore-working-copy -r HEAD@git'
symbol = 'jj:git≠'
style = 'bold red'
